### PR TITLE
Modifyies behavior to allow multiple algorithms from crystal language

### PR DESCRIPTION
**Pull request by Xosmond**
Hey I just did an update for crystal 0.28.0. Let me know what do you think.

### CODE REVIEW

**Comment by philnash** [comment]
This looks good. I only got time to half check this today, but will try to get back to it tomorrow.
Thanks!

**Comment by philnash** [comment]
I apologise it took me ages to get back to this.

I'm going to modify this slightly. According to [RFC 4226](https://tools.ietf.org/html/rfc4226) (HOTP) the only available hashing algorithm is HMAC-SHA-1.

On the other hand, [RFC 6238](https://tools.ietf.org/html/rfc6238) (TOTP) allows for HMAC-SHA-256 and HMAC-SHA-512.

So I'm going to restrict the available algorithms (and write tests for the new ones, the RFC provides examples, which is nice). Otherwise, this is great, thanks.

**Comment by philnash** [comment]
This is added, including my own additions, in version 0.3.0 of the gem. Thanks for kicking off this change and sorry again for the delay with it.

**Comment by Xosmond** [comment]
@philnash Hey Great you are back, thanks for your work :)

**Pull request merged**
